version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Use Java 17 runtime
    commands:
      - echo "Installing Gradle" # Install Gradle
      - curl -sL https://services.gradle.org/distributions/gradle-8.4-bin.zip -o gradle.zip
      - unzip -q gradle.zip
      - export PATH=$PATH:$PWD/gradle-8.4/bin

  build:
    commands:
      - echo "Executing build commands"

      - echo "Downloading application.properties from S3..."
      - aws s3 cp s3://etta-docker-bucket/application.properties application.properties
      - echo "Moving application.properties to the resource folder..."
      - mv application.properties src/main/resources/

      - echo "Downloading Dockerrun.aws.json from S3..."
      - aws s3 cp s3://docker-json-run/Dockerrun.aws.json Dockerrun.aws.json

      - chmod +x ./gradlew  # Add this line to grant executable permissions
      - ./gradlew clean build

      - echo "Creating Dockerfile..."
      - echo "FROM openjdk:17-jdk" > Dockerfile
      - echo "WORKDIR /app" >> Dockerfile
      - echo "COPY build/libs/edtech-0.0.1-SNAPSHOT.jar /app/demo.jar" >> Dockerfile
      - echo "EXPOSE 8080" >> Dockerfile
      - echo "CMD [\"java\", \"-jar\", \"demo.jar\"]" >> Dockerfile

      - echo log in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:latest .

      - echo Tagging Docker image...
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest

artifacts:
  files:
    - build/libs/edtech-0.0.1-SNAPSHOT.jar  # Adjust the path according to your Gradle build output
    - Dockerfile
    - Dockerrun.aws.json