version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Use Java 17 runtime
    commands:
      - echo "Installing Gradle"
      - curl -sL https://services.gradle.org/distributions/gradle-8.4-bin.zip -o gradle.zip
      - unzip -q gradle.zip
      - export PATH=$PATH:$PWD/gradle-8.4/bin
  pre_build:
    commands:
      - echo "Executing pre-build commands"
      # Any pre-build commands you need, such as installing dependencies, setting up environment, etc.
      - export "spring.datasource.url=jdbc:mysql://etta-dev.cl2gg26am2wz.us-east-1.rds.amazonaws.com:3306/etta-dev"
      - export "spring.datasource.username=admin"
      - export "spring.datasource.password=Camrin0208"
      - export "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect"
      - export "spring.jpa.hibernate.ddl-auto=update"
  build:
    commands:
      - echo "Executing build commands"
      - chmod +x ./gradlew  # Add this line to grant executable permissions
      - ./gradlew clean build
  post_build:
    commands:
      - echo "Executing post-build commands"
      # Any post-build commands such as running tests, packaging artifacts, deploying, etc.

artifacts:
  files:
    - build/libs/edtech-0.0.1-SNAPSHOT.jar  # Adjust the path according to your Gradle build output
