version: 0.2

env:
  variables:
    DB_URL: $DB_URL

phases:
  install:
    runtime-versions:
      java: corretto17  # Use Java 17 runtime
    commands:
      - echo "Installing Gradle"
      - curl -sL https://services.gradle.org/distributions/gradle-8.4-bin.zip -o gradle.zip
      - unzip -q gradle.zip
      - export PATH=$PATH:$PWD/gradle-8.4/bin
    pre_build:
      commands:
        - aws --version
        #- echo $AWS_DEFAULT_REGION
        #- aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
        #- REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/etta-ecr-docker
        #- COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        #- IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo $DB_URL
      - echo $DB_USERNAME
      - echo $DB_PASSWORD
      - echo $DB_DRIVER
      - echo $REPOSITORY_URI

      - echo "Executing build commands"

      - chmod +x ./gradlew  # Add this line to grant executable permissions
      - ./gradlew clean build

      - echo log in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:latest .

      - echo Tagging Docker image...
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      #- echo write definitions file...
      #- printf '[{"name":"exp-code-pipeline","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - build/libs/edtech-0.0.1-SNAPSHOT.jar  # Adjust the path according to your Gradle build output
